# Generated by Django 5.1 on 2024-08-11 20:56

import content.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=300, upload_to=content.utils.page_image_path),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=content.utils.page_file_path),
        ),
    ]
