# Generated by Django 5.1 on 2024-08-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_pagecontent_hero_image_alter_pagecontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
