# Generated by Django 5.1 on 2024-08-14 07:35

import content.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_pagecontent_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_description', models.TextField(blank=True, verbose_name='Title Description')),
                ('hero_image', models.ImageField(blank=True, max_length=300, upload_to=content.utils.page_image_path)),
                ('paragraph_1', models.TextField(blank=True, verbose_name='paragraph')),
                ('paragraph_2', models.TextField(blank=True, verbose_name='paragraph')),
                ('paragraph_3', models.TextField(blank=True, verbose_name='paragraph')),
                ('paragraph_4', models.TextField(blank=True, verbose_name='paragraph')),
                ('paragraph_5', models.TextField(blank=True, verbose_name='paragraph')),
                ('file', models.FileField(blank=True, null=True, upload_to=content.utils.page_file_path)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, max_length=300, upload_to=content.utils.page_image_path)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.ImageField(blank=True, upload_to=content.utils.image_thumbnail_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_gallery', to='content.articles')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
