# Generated by Django 5.1 on 2024-08-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_articles_articlegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
