# Generated by Django 5.1 on 2024-08-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_articles_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='header_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='header_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='header_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='header_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='header_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='paragraph_6',
            field=models.TextField(blank=True, verbose_name='paragraph'),
        ),
        migrations.AddField(
            model_name='articles',
            name='paragraph_7',
            field=models.TextField(blank=True, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('article', 'Article')], max_length=200),
        ),
    ]
