# Generated by Django 5.1 on 2024-08-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_articles_header_1_articles_header_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='paragraph_6',
            field=models.TextField(blank=True, verbose_name='paragraph'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='paragraph_7',
            field=models.TextField(blank=True, verbose_name='paragraph'),
        ),
    ]
