# Generated by Django 5.1 on 2024-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_pagecontent_paragraph_6_pagecontent_paragraph_7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegallery',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagegallery',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
