# Generated by Django 5.1 on 2024-08-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_articlegallery_name_alter_articles_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='header_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='header_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='header_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='header_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='header_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='paragraph_1',
            field=models.TextField(blank=True, null=True, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='paragraph_2',
            field=models.TextField(blank=True, null=True, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='paragraph_3',
            field=models.TextField(blank=True, null=True, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='paragraph_4',
            field=models.TextField(blank=True, null=True, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='paragraph_5',
            field=models.TextField(blank=True, null=True, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='paragraph_6',
            field=models.TextField(blank=True, null=True, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='paragraph_7',
            field=models.TextField(blank=True, null=True, verbose_name='paragraph'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title_description',
            field=models.TextField(blank=True, null=True, verbose_name='Title Description'),
        ),
    ]
