# Generated by Django 5.1 on 2024-08-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_articles_active_alter_articles_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
