# Generated by Django 5.1 on 2024-08-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_articles_title_alter_pagecontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
