# Generated by Django 5.1 on 2024-08-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_message', to='content.message'),
        ),
    ]
